single_words = [
         {"src": "http://www.handspeak.com/word/a/account-fs.mp4", "word": "account"},
         {"src": "http://www.handspeak.com/word/a/aids-fs.mp4", "word": "aids"},
         {"src": "http://www.handspeak.com/word/a/air-fs.mp4", "word": "air"},
         {"src": "http://www.handspeak.com/word/a/ally-fs.mp4", "word": "ally"},
         {"src": "http://www.handspeak.com/word/a/apartment.mp4", "word": "apt"},
         {"src": "http://www.handspeak.com/word/a/art-fs.mp4", "word": "art"},
         {"src": "http://www.handspeak.com/word/a/asl-fs.mp4", "word": "asl"},
         {"src": "http://www.handspeak.com/word/b/back-fs.mp4", "word": "back"},
         {"src": "http://www.handspeak.com/word/b/bail-fs.mp4", "word": "bail"},
         {"src": "http://www.handspeak.com/word/b/bank-fs.mp4", "word": "bank"},
         {"src": "http://www.handspeak.com/word/b/bar-fs.mp4", "word": "bar"},
         {"src": "http://www.handspeak.com/word/b/bee-fs.mp4", "word": "bee"},
         {"src": "http://www.handspeak.com/word/b/beef-fs.mp4", "word": "beef"},
         {"src": "http://www.handspeak.com/word/b/beet-fs.mp4", "word": "beet"},
         {"src": "http://www.handspeak.com/word/b/bill-fs.mp4", "word": "bill"},
         {"src": "http://www.handspeak.com/word/b/billion-fs.mp4", "word": "billion"},
         {"src": "http://www.handspeak.com/word/b/but-fs.mp4", "word": "but"},
         {"src": "http://www.handspeak.com/word/b/burn-fs.mp4", "word": "burn"},
         {"src": "http://www.handspeak.com/word/b/bursary-fs.mp4", "word": "bursary"},
         {"src": "http://www.handspeak.com/word/c/cabin-fs.mp4", "word": "cabin"},
         {"src": "http://www.handspeak.com/word/c/cable-fs.mp4", "word": "cable"},
         {"src": "http://www.handspeak.com/word/c/campus-fs.mp4", "word": "campus"},
         {"src": "http://www.handspeak.com/word/c/cancer-fs.mp4", "word": "cancer"},
         {"src": "http://www.handspeak.com/word/c/car-fs.mp4", "word": "car"},
         {"src": "http://www.handspeak.com/word/c/cash-fs.mp4", "word": "cash"},
         {"src": "http://www.handspeak.com/word/c/cast-fs.mp4", "word": "cast"},
         {"src": "http://www.handspeak.com/word/c/cave-fs.mp4", "word": "cave"},
         {"src": "http://www.handspeak.com/word/c/cavity-fs.mp4", "word": "cavity"},
         {"src": "http://www.handspeak.com/word/c/cell-fs.mp4", "word": "cell"},
         {"src": "http://www.handspeak.com/word/c/cement-fs.mp4", "word": "cement"},
         {"src": "http://www.handspeak.com/word/c/ceramic-fs.mp4", "word": "ceramic"},
         {"src": "http://www.handspeak.com/word/c/chalk-fs.mp4", "word": "chalk"},
         {"src": "http://www.handspeak.com/word/c/chef-fs.mp4", "word": "chef"},
         {"src": "http://www.handspeak.com/word/c/civil-fs.mp4", "word": "civil"},
         {"src": "http://www.handspeak.com/word/c/clay-fs.mp4", "word": "clay"},
         {"src": "http://www.handspeak.com/word/c/claim-fs.mp4", "word": "claim"},
         {"src": "http://www.handspeak.com/word/c/clinic-fs.mp4", "word": "clinic"},
         {"src": "http://www.handspeak.com/word/c/clot-fs.mp4", "word": "clot"},
         {"src": "http://www.handspeak.com/word/c/club-fs.mp4", "word": "club"},
         {"src": "http://www.handspeak.com/word/c/clue-fs.mp4", "word": "clue"},
         {"src": "http://www.handspeak.com/word/c/coda-fs.mp4", "word": "coda"},
         {"src": "http://www.handspeak.com/word/c/cocoa-fs.mp4", "word": "cocoa"},
         {"src": "http://www.handspeak.com/word/c/coke-fs.mp4", "word": "coke"},
         {"src": "http://www.handspeak.com/word/c/coma-fs.mp4", "word": "coma"},
         {"src": "http://www.handspeak.com/word/c/commision-fs.mp4", "word": "commission"},
         {"src": "http://www.handspeak.com/word/c/condominium.mp4", "word": "condo"},
         {"src": "http://www.handspeak.com/word/c/cool-fs.mp4", "word": "cool"},
         {"src": "http://www.handspeak.com/word/c/core-fs.mp4", "word": "core"},
         {"src": "http://www.handspeak.com/word/c/cork-fs.mp4", "word": "cork"},
         {"src": "http://www.handspeak.com/word/c/comatose-fs.mp4", "word": "coma"},
         {"src": "http://www.handspeak.com/word/c/comics-fs.mp4", "word": "comics"},
         {"src": "http://www.handspeak.com/word/c/cottage-fs.mp4", "word": "cottage"},
         {"src": "http://www.handspeak.com/word/c/cotton-fs.mp4", "word": "cotton"},
         {"src": "http://www.handspeak.com/word/c/council-fs.mp4", "word": "council"},
         {"src": "http://www.handspeak.com/word/c/cozy-fs.mp4", "word": "cozy"},
         {"src": "http://www.handspeak.com/word/c/craft-fs.mp4", "word": "craft"},
         {"src": "http://www.handspeak.com/word/c/crime-fs.mp4", "word": "crime"},
         {"src": "http://www.handspeak.com/word/c/crop-fs.mp4", "word": "crop"},
         {"src": "http://www.handspeak.com/word/c/crystal-fs.mp4", "word": "crystal"},
         {"src": "http://www.handspeak.com/word/c/cult-fs.mp4", "word": "cult"},
         {"src": "http://www.handspeak.com/word/c/custody-fs.mp4", "word": "custody"},
         {"src": "http://www.handspeak.com/word/c/cyst-fs.mp4", "word": "cyst"},
         {"src": "http://www.handspeak.com/word/d/data-fs.mp4", "word": "data"},
         {"src": "http://www.handspeak.com/word/d/date-fs.mp4", "word": "date"},
         {"src": "http://www.handspeak.com/word/d/deal-fs.mp4", "word": "deal"},
         {"src": "http://www.handspeak.com/word/d/deli-fs.mp4", "word": "deli"},
         {"src": "http://www.handspeak.com/word/d/dene-fs.mp4", "word": "dene"},
         {"src": "http://www.handspeak.com/word/d/diet-fs.mp4", "word": "diet"},
         {"src": "http://www.handspeak.com/word/d/disco-fs.mp4", "word": "disco"},
         {"src": "http://www.handspeak.com/word/d/dna-fs.mp4", "word": "dna"},
         {"src": "http://www.handspeak.com/word/d/dog-fs.mp4", "word": "dog"},
         {"src": "http://www.handspeak.com/word/d/draft-fs.mp4", "word": "draft"},
         {"src": "http://www.handspeak.com/word/d/drug-fs.mp4", "word": "drug"},
         {"src": "http://www.handspeak.com/word/d/due-fs.mp4", "word": "due"},
         {"src": "http://www.handspeak.com/word/d/dust-fs.mp4", "word": "dust"},
         {"src": "http://www.handspeak.com/word/d/dvd-fs.mp4", "word": "dvd"},
         {"src": "http://www.handspeak.com/word/e/extra-fs.mp4", "word": "extra"},
         {"src": "http://www.handspeak.com/word/f/fact-fs.mp4", "word": "fact"},
         {"src": "http://www.handspeak.com/word/f/fate-fs.mp4", "word": "fate"},
         {"src": "http://www.handspeak.com/word/f/fee-fs.mp4", "word": "fee"},
         {"src": "http://www.handspeak.com/word/f/flu-fs.mp4", "word": "flu"},
         {"src": "http://www.handspeak.com/word/f/fly-fs.mp4", "word": "fly"},
         {"src": "http://www.handspeak.com/word/f/fog-fs.mp4", "word": "fog"},
         {"src": "http://www.handspeak.com/word/f/foot-fs.mp4", "word": "foot"},
         {"src": "http://www.handspeak.com/word/f/free-fs.mp4", "word": "free"},
         {"src": "http://www.handspeak.com/word/f/fun-fs.mp4", "word": "fun"},
         {"src": "http://www.handspeak.com/word/g/ghetto-fs.mp4", "word": "ghetto"},
         {"src": "http://www.handspeak.com/word/g/grant-fs.mp4", "word": "grant"},
         {"src": "http://www.handspeak.com/word/g/gift-fs.mp4", "word": "gift"},
         {"src": "http://www.handspeak.com/word/g/gas-fs.mp4", "word": "gas"},
         {"src": "http://www.handspeak.com/word/h/hiv-fs.mp4", "word": "hiv"},
         {"src": "http://www.handspeak.com/word/h/hurt-fs.mp4", "word": "hurt"},
         {"src": "http://www.handspeak.com/word/h/hall-fs.mp4", "word": "hall"},
         {"src": "http://www.handspeak.com/word/h/hero-fs.mp4", "word": "hero"},
         {"src": "http://www.handspeak.com/word/h/hole-fs.mp4", "word": "hole"},
         {"src": "http://www.handspeak.com/word/i/ink-fs.mp4", "word": "ink"},
         {"src": "http://www.handspeak.com/word/i/invoice-fs.mp4", "word": "invoice"},
         {"src": "http://www.handspeak.com/word/i/if-fs.mp4", "word": "if"},
         {"src": "http://www.handspeak.com/word/i/ice-fs.mp4", "word": "ice"},
         {"src": "http://www.handspeak.com/word/j/jerk-fs.mp4", "word": "jerk"},
         {"src": "http://www.handspeak.com/word/j/jersey-fs.mp4", "word": "jersey"},
         {"src": "http://www.handspeak.com/word/j/joke-fs.mp4", "word": "joke"},
         {"src": "http://www.handspeak.com/word/j/junk-fs.mp4", "word": "junk"},
         {"src": "http://www.handspeak.com/word/l/lego-fs.mp4", "word": "lego"},
         {"src": "http://www.handspeak.com/word/l/logo-fs.mp4", "word": "logo"},
         {"src": "http://www.handspeak.com/word/l/lynx-fs.mp4", "word": "lynx"},
         {"src": "http://www.handspeak.com/word/m/mayonnaise.mp4", "word": "mayo"},
         {"src": "http://www.handspeak.com/word/m/million-fs.mp4", "word": "million"},
         {"src": "http://www.handspeak.com/word/m/mini-fs.mp4", "word": "mini"},
         {"src": "http://www.handspeak.com/word/m/moral-fs.mp4", "word": "moral"},
         {"src": "http://www.handspeak.com/word/m/mortgage-fs.mp4", "word": "mortgage"},
         {"src": "http://www.handspeak.com/word/m/mold-fs.mp4", "word": "mold"},
         {"src": "http://www.handspeak.com/word/m/mri-fs.mp4", "word": "mri"},
         {"src": "http://www.handspeak.com/word/m/mud-fs.mp4", "word": "mud"},
         {"src": "http://www.handspeak.com/word/m/myth-fs.mp4", "word": "myth"},
         {"src": "http://www.handspeak.com/word/n/numb-fs.mp4", "word": "numb"},
         {"src": "http://www.handspeak.com/word/o/obe-fs.mp4", "word": "obe"},
         {"src": "http://www.handspeak.com/word/o/ocd-fs.mp4", "word": "ocd"},
         {"src": "http://www.handspeak.com/word/o/odd-fs.mp4", "word": "odd"},
         {"src": "http://www.handspeak.com/word/o/off-fs.mp4", "word": "off"},
         {"src": "http://www.handspeak.com/word/o/own-fs.mp4", "word": "own"},
         {"src": "http://www.handspeak.com/word/o/oil-fs.mp4", "word": "oil"},
         {"src": "http://www.handspeak.com/word/o/on-fs.mp4", "word": "on"},
         {"src": "http://www.handspeak.com/word/o/or.mp4", "word": "or"},
         {"src": "http://www.handspeak.com/word/p/pea-fs.mp4", "word": "pea"},
         {"src": "http://www.handspeak.com/word/p/phoneme-fs.mp4", "word": "phoneme"},
         {"src": "http://www.handspeak.com/word/p/pizza.mp4", "word": "pizza"},
         {"src": "http://www.handspeak.com/word/p/prom-fs.mp4", "word": "prom"},
         {"src": "http://www.handspeak.com/word/p/pet-fs.mp4", "word": "pet"},
         {"src": "http://www.handspeak.com/word/p/pudding-fs.mp4", "word": "pudding"},
         {"src": "http://www.handspeak.com/word/q/quiz-fs.mp4", "word": "quiz"},
         {"src": "http://www.handspeak.com/word/q/quota-fs.mp4", "word": "quota"},
         {"src": "http://www.handspeak.com/word/r/recipe-fs.mp4", "word": "recipe"},
         {"src": "http://www.handspeak.com/word/r/root-fs.mp4", "word": "root"},
         {"src": "http://www.handspeak.com/word/r/rich-fs.mp4", "word": "rich"},
         {"src": "http://www.handspeak.com/word/r/risk-fs.mp4", "word": "risk"},
         {"src": "http://www.handspeak.com/word/r/rabbi-fs.mp4", "word": "rabbi"},
         {"src": "http://www.handspeak.com/word/r/rice-fs.mp4", "word": "rice"},
         {"src": "http://www.handspeak.com/word/r/rape-fs.mp4", "word": "rape"},
         {"src": "http://www.handspeak.com/word/r/rug-fs.mp4", "word": "rug"},
         {"src": "http://www.handspeak.com/word/r/rare-fs.mp4", "word": "rare"},
         {"src": "http://www.handspeak.com/word/s/siesta-fs.mp4", "word": "siesta"},
         {"src": "http://www.handspeak.com/word/s/snack-fs.mp4", "word": "snack"},
         {"src": "http://www.handspeak.com/word/s/slum-fs.mp4", "word": "slum"},
         {"src": "http://www.handspeak.com/word/s/sue-fs.mp4", "word": "sue"},
         {"src": "http://www.handspeak.com/word/s/style-fs.mp4", "word": "style"},
         {"src": "http://www.handspeak.com/word/s/sure-fs.mp4", "word": "sure"},
         {"src": "http://www.handspeak.com/word/s/so-fs.mp4", "word": "so"},
         {"src": "http://www.handspeak.com/word/t/taco-fs.mp4", "word": "taco"},
         {"src": "http://www.handspeak.com/word/t/tar-fs.mp4", "word": "tar"},
         {"src": "http://www.handspeak.com/word/t/tax.mp4", "word": "tax"},
         {"src": "http://www.handspeak.com/word/t/too-fs.mp4", "word": "too"},
         {"src": "http://www.handspeak.com/word/t/tool-fs.mp4", "word": "tool"},
         {"src": "http://www.handspeak.com/word/t/toy-fs.mp4", "word": "toy"},
         {"src": "http://www.handspeak.com/word/t/truck-fs.mp4", "word": "truck"},
         {"src": "http://www.handspeak.com/word/t/tryout-fs.mp4", "word": "try out"},
         {"src": "http://www.handspeak.com/word/t/tuition-fs.mp4", "word": "tuition"},
         {"src": "http://www.handspeak.com/word/u/update-fs.mp4", "word": "update"},
         {"src": "http://www.handspeak.com/word/v/vanilla-fs.mp4", "word": "vanilla"},
         {"src": "http://www.handspeak.com/word/v/van-fs.mp4", "word": "van"},
         {"src": "http://www.handspeak.com/word/w/what-fs.mp4", "word": "what"},
         {"src": "http://www.handspeak.com/word/w/wfd-fs.mp4", "word": "wfd"},
         {"src": "http://www.handspeak.com/word/w/will-fs.mp4", "word": "will"},
         {"src": "http://www.handspeak.com/word/w/wild-fs.mp4", "word": "wild"},
         {"src": "http://www.handspeak.com/word/y/yard-fs.mp4", "word": "yard"},
         {"src": "http://www.handspeak.com/word/y/yoyo-fs.mp4", "word": "yoyo"},
         {"src": "http://www.handspeak.com/word/y/yoga-fs.mp4", "word": "yoga"},
         {"src": "http://www.handspeak.com/word/z/zoo-fs.mp4", "word": "zoo"}
        ]

double_words = [
  {"src": "http://www.handspeak.com/spell/practice/double-word/bar-bag.mp4", "word": "bar bag"},
  {"src": "http://www.handspeak.com/spell/practice/double-word/bar-war.mp4", "word": "bar war"},
  {"src": "http://www.handspeak.com/spell/practice/double-word/bark-park.mp4", "word": "bark park"},
  {"src": "http://www.handspeak.com/spell/practice/double-word/bat-ban.mp4", "word": "bat ban"},
  {"src": "http://www.handspeak.com/spell/practice/double-word/cap-can.mp4", "word": "cap can"},
  {"src": "http://www.handspeak.com/spell/practice/double-word/cap-cop.mp4", "word": "cap cop"},
  {"src": "http://www.handspeak.com/spell/practice/double-word/cart-tart.mp4", "word": "cart tart"},
  {"src": "http://www.handspeak.com/spell/practice/double-word/dose-lose.mp4", "word": "dose lose"},
  {"src": "http://www.handspeak.com/spell/practice/double-word/dot-dog.mp4", "word": "dot dog"},
{"src": "http://www.handspeak.com/spell/practice/double-word/eat-ear.mp4", "word": "eat ear"},
{"src": "http://www.handspeak.com/spell/practice/double-word/farm-firm.mp4", "word": "farm firm"},
{"src": "http://www.handspeak.com/spell/practice/double-word/fog-bag.mp4", "word": "fog bag"},
{"src": "http://www.handspeak.com/spell/practice/double-word/full-dull.mp4", "word": "full dull"},
{"src": "http://www.handspeak.com/spell/practice/double-word/full-pull.mp4", "word": "full pull"},
{"src": "http://www.handspeak.com/spell/practice/double-word/hail-pail.mp4", "word": "hail pail"},
{"src": "http://www.handspeak.com/spell/practice/double-word/hall-wall.mp4", "word": "hall wall"},
{"src": "http://www.handspeak.com/spell/practice/double-word/hat-has.mp4", "word": "hat has"},
{"src": "http://www.handspeak.com/spell/practice/double-word/key-keg.mp4", "word": "key keg"},
{"src": "http://www.handspeak.com/spell/practice/double-word/lake-fake.mp4", "word": "lake fake"},
{"src": "http://www.handspeak.com/spell/practice/double-word/lock-sock.mp4", "word": "lock sock"},
{"src": "http://www.handspeak.com/spell/practice/double-word/map-mop.mp4", "word": "map mop"},
{"src": "http://www.handspeak.com/spell/practice/double-word/nap-tap.mp4", "word": "nap tap"},
{"src": "http://www.handspeak.com/spell/practice/double-word/pat-put.mp4", "word": "pat put"},
{"src": "http://www.handspeak.com/spell/practice/double-word/pear-near.mp4", "word": "pear near"},
{"src": "http://www.handspeak.com/spell/practice/double-word/pit-put.mp4", "word": "pit put"},
{"src": "http://www.handspeak.com/spell/practice/double-word/pox-box.mp4", "word": "pox box"},
{"src": "http://www.handspeak.com/spell/practice/double-word/pug-put.mp4", "word": "pug put"},
{"src": "http://www.handspeak.com/spell/practice/double-word/rag-rap.mp4", "word": "rag rap"},
{"src": "http://www.handspeak.com/spell/practice/double-word/rap-rip.mp4", "word": "rap rip"},
{"src": "http://www.handspeak.com/spell/practice/double-word/rear-rare.mp4", "word": "rear rare"},
{"src": "http://www.handspeak.com/spell/practice/double-word/read-reap.mp4", "word": "read reap"},
{"src": "http://www.handspeak.com/spell/practice/double-word/rent-cent.mp4", "word": "rent cent"},
{"src": "http://www.handspeak.com/spell/practice/double-word/rub-tub.mp4", "word": "rub tub"},
{"src": "http://www.handspeak.com/spell/practice/double-word/sale-sake.mp4", "word": "sale sake"},
{"src": "http://www.handspeak.com/spell/practice/double-word/sap-tap.mp4", "word": "sap tap"},
{"src": "http://www.handspeak.com/spell/practice/double-word/seed-deed.mp4", "word": "seed deed"},
{"src": "http://www.handspeak.com/spell/practice/double-word/set-net.mp4", "word": "set net"},
{"src": "http://www.handspeak.com/spell/practice/double-word/sing-ring.mp4", "word": "sing ring"},
{"src": "http://www.handspeak.com/spell/practice/double-word/sit-set.mp4", "word": "sit set"},
{"src": "http://www.handspeak.com/spell/practice/double-word/soul-soup.mp4", "word": "soul soup"},
{"src": "http://www.handspeak.com/spell/practice/double-word/tap-tar.mp4", "word": "tap tar"},
{"src": "http://www.handspeak.com/spell/practice/double-word/tap-tip.mp4", "word": "tap tip"},
{"src": "http://www.handspeak.com/spell/practice/double-word/tar-tan.mp4", "word": "tar tan"},
{"src": "http://www.handspeak.com/spell/practice/double-word/tar-tap.mp4", "word": "tar tap"},
{"src": "http://www.handspeak.com/spell/practice/double-word/teal seal.mp4", "word": "teal seal"},
{"src": "http://www.handspeak.com/spell/practice/double-word/tip-tap.mp4", "word": "tip tap"},
{"src": "http://www.handspeak.com/spell/practice/double-word/tram-trap.mp4", "word": "tram trap"},
{"src": "http://www.handspeak.com/spell/practice/double-word/trap-wrap.mp4", "word": "trap wrap"},
{"src": "http://www.handspeak.com/spell/practice/double-word/wax-max.mp4", "word": "wax max"},
{"src": "http://www.handspeak.com/spell/practice/double-word/well-hell.mp4", "word": "well hell"}
]

import urllib3
http = urllib3.PoolManager()

for word in single_words:
    r = http.request('GET', word['src'], preload_content=False)

    with open("C:/Users/riley/DeepLetters/Data/HandSpeak/Single/"+word['word']+".mp4", 'wb') as out:
        while True:
            data = r.read(1024)
            if not data:
                break
            out.write(data)

    r.release_conn()

for word in double_words:
    r = http.request('GET', word['src'], preload_content=False)

    with open("C:/Users/riley/DeepLetters/Data/HandSpeak/Double/" + word['word'] + ".mp4", 'wb') as out:
        while True:
            data = r.read(1024)
            if not data:
                break
            out.write(data)

    r.release_conn()
